### PR TITLE
fix cl_async & maxfps

### PR DESCRIPTION
**Pull request by sthalik**
The QVF_VIDEOSYNC flag isn't set anywhere.

Also we can't predict vsync behavior: GPU drivers on
Windows and Linux allow for forcing vsync on or off.

### CODE REVIEW

**Comment by tojestzart** [comment]
dont know what u talking about but want to comment as moron,
in jumpmod we having command called "!fps" and it shows real fps comparing to setup, seems it is whats your talking about , usually its above setup

**Comment by sthalik** [comment]
@tojestzart try this from the console

``
/draw cl_fps 200 200
/draw cl_mps 200 210
/draw cl_ups 200 220
``

**Comment by sthalik** [comment]
And don't worry, barely anyone playing games understands this stuff.

Jak graliśmy moje ponad pół życia temu to nikt nie wiedział o tym maxfps i myśleli, że 5 w górę robi różnicę.

**Comment by sthalik** [comment]
BUT you could help testing a build. I'm too rusty to play online against random players. Of course it can't have anti-cheat module in.

**Comment by tojestzart** [comment]
nie moge teraz dac ci prawdziwych wynikow z asus k56cb bo jestem na jakims gownie od brata t101-ha mam matryce zbitą musisz czekac albo znaleźć kogoś innego , pozdro,
 broken english:
i cant give u actually fair results since im using tablet now ( asus t101-ha), i have broken lcd screen in my laptop, u need to wait or, find someone else, regards

**Comment by sthalik** [comment]
@tojestzart know anyone else playing? I parted with `#q2.pl` on bad terms. Long story ;)

Worries and best wishes about the broken display.

**Comment by tojestzart** [comment]
@sthalik   just join #q2scene discord or read a little fajnyboard , or tastyspleen , i would invite you for discord.q2jump.net but actually its racist and u cant join in case you dont have "skills" thanls to @fishxz

**Comment by sthalik** [comment]
Ask him. I can stand racism, got a thick skin ;)

**Comment by tojestzart** [comment]
@sthalik  actually im banned here for REASON, so i dont say im clear, but, when u join they will ask u "WHO ARE U"

**Comment by fishxz** [comment]
hmm, interesting to read this here. you were banned for a reason and when i read your post here it was the right decision.

 to make it clear and safe the repution of our community. it was not about racism and stuff he got banned. it was his insulting behavior.

**Comment by sthalik** [comment]
@fishxz you can send me an invite link privately via email -- `sthalik@misaki.pl` if you so wish.

**Comment by sthalik** [comment]
There's no way to allow millisecond-accurate times while keeping the invariant in `Qcommon_Frame` of at least 1 msec passing.

In fact, allowing only msec resolution results in more consistent frame timings.

**Pull request closed without merging**
