### PR TITLE
WIP: Rerelease game interface

### PR DESCRIPTION
**Pull request by res2k**
This is some early work to move towards supporting the game interface changes introduced by the Quake 2 rerelease.
The game interface changes are complex enough to require a piecemeal approach to change them.
However, I'd like to request some early feedback on the approach I've chosen - and also to find out to what extent you're interested in these changes...

Points of interest:
* Added "a server private sv_entity_t"
* Includes a proxy game to keep support for version 3 games.

So, do you already have a plan/intentions wrt supporting the "rerelease" game interface?
And what's your opinion on the proxy game idea?

### CODE REVIEW

**Comment by skullernet** [comment]
Hi, I gave this some pondering and at this point I'm not interested in supporting re-release game API and/or network protocol in Q2PRO. Required changes are way too invasive if backward compatibility with original Quake 2 is to be kept. I'm interested however in having re-release single player campaign playable.

I've skimmed though your changes and overall I must say I'm not very fond of this wrapper approach. Wrapping nearly every game API call with sync_edicts_server_to_game()/sync_edicts_game_to_server() sounds terrible. I can imagine this easily causing performance hit. At this point I'd say if you really want to support re-release game API, just ditch backward compatibility completely. It's not worth the hassle.

Did you notice I'm adding re-release support via `protocol-limits` branch currently? Instead of bending the server to support re-release game API, I took the approach of [porting](https://github.com/skullernet/q2pro-rerelease-dll) re-release game library to game API version 3 (with some extensions, like raised MAX_EDICTS/MAX_MODELS/etc limits), removing all proprietary KEX APIs in the process. This avoids any kind of wrapper approach, and also provides an opportunity for authors of existing Quake 2 mods to easily gain access to extended features like raised protocol limits with minimal changes from the game side (you literally just recompile with raised MAX_EDICTS definition and that's it), compared to rather invasive changes required when porting to re-release game API.

**Comment by res2k** [comment]
Hi, thanks for pondering :)
So, in general, my main desire would also be to have support for rerelease single player content.
However, I'm not sure stripping rerelease features may work for all rerelease maps: I've been told using the "new" game library is advisable for full compatibility (see https://github.com/NVIDIA/Q2RTX/issues/300#issuecomment-1682202790). So there's probably value in supporting the new interface for the single player content.
Beyond vanilla singleplayer, there's probably some likelihood that 3rd party mods are updated to the new interface as well, perhaps to make use of the new features it offers, perhaps to be playable with the closed source rerelease distribution... these mods would obviously require "proper" game interface support.

As for "backward compatibility" ... Well, yes, the eventual goal should be to natively use the updated interface.
However, I also think backward compatibility can be a nice bonus. But it doesn't have to be in-engine, it could well we a separate game library; but some support from the engine would certainly be convenient.

As for the wrapping approach... I couldn't think of a better one. Since communication between game and engine goes through shared data structures, the only way I could think of translating between the different versions is to copy data around between old and new. And without a convenient way to detect which entities changed (if you know one, please tell me), iterating over all structures seems unavoidable.
Could this have a performance impact? I'm not so sure it would make a measurable differences. Yes, it's looping over each entity, however, there's still a cap of 8192 stipulated by the new game interface. The operations performed on the entities are simple, just data copying. I'm thinking a modern processor can probably cope with that without producing a noticeable drop in performance.

And yes, I've seen the `protocol-limits` branch, and that made me wonder what your intentions wrt rerelease support are, if any.

**Comment by skullernet** [comment]
> However, I'm not sure stripping rerelease features may work for all rerelease maps: I've been told using the "new" game library is advisable for full compatibility

Pretty sure everything will work, as far as entity behavior and map mechanics are concerned. You won't get eyecandy features such as fog or shadow lights, but Q2PRO has never cared about them. If you are specifically talking about the new `clip` function, it has been implemented in Q2PRO as an extension to regular `trace`. FYI, I've played through entirety of CotM in Q2PRO with "stripped" library and there were no major issues whatsoever.

> Beyond vanilla singleplayer, there's probably some likelihood that 3rd party mods are updated to the new interface as well, perhaps to make use of the new features it offers, perhaps to be playable with the closed source rerelease distribution...

That still needs to happen. Also IANAL, but I'm not sure about how that will ever work from legal point of view: proprietary application loading GPL game module.

> Well, yes, the eventual goal should be to natively use the updated interface.

I'm not so sure... Although re-release changes nothing fundamentally in the engine, it touches enough important things that change game balance, specifically server tick rate and pmove precision. New players coming to Quake 2 may not care about it, but a lot of older players care. Thus preserving original game interface and original gameplay should be an equally important goal.

>  I'm thinking a modern processor can probably cope with that without producing a noticeable drop in performance.

Modern workstations/gaming rigs sure are fast enough for this... But when you are hosting 20+ game server instances on a shared VPS additional overhead becomes important.

**Comment by res2k** [comment]
> Pretty sure everything will work, as far as entity behavior and map mechanics are concerned. You won't get eyecandy features such as fog or shadow lights, but Q2PRO has never cared about them. If you are specifically talking about the new `clip` function, it has been implemented in Q2PRO as an extension to regular `trace`. FYI, I've played through entirety of CotM in Q2PRO with "stripped" library and there were no major issues whatsoever.

Yeah, `clip` is what I was thinking of.
But FWIW, overloading `trace` and triggering different behaviour by setting a specific bit in a pointer ... that's kind of hacky.

> That still needs to happen. Also IANAL, but I'm not sure about how that will ever work from legal point of view: proprietary application loading GPL game module.

Happen, maybe, but there seems to be at least interest in such conversions:
https://github.com/packetflinger/openra2/issues/41
https://github.com/actionquake/quake2-rerelease-dll

> I'm not so sure... Although re-release changes nothing fundamentally in the engine, it touches enough important things that change game balance, specifically server tick rate and pmove precision. New players coming to Quake 2 may not care about it, but a lot of older players care. Thus preserving original game interface and original gameplay should be an equally important goal.

As far as the tick rate is concerned, that's server-controlled and just passed into the game - so theoretically, a well-coded game library should be able to run with different tick rates, including the "old" 10hz rate.
Pmove is also entirely handled by the game (and cgame) module, so at least in theory it should be possible to retain any old behaviour as well, here.

> Modern workstations/gaming rigs sure are fast enough for this... But when you are hosting 20+ game server instances on a shared VPS additional overhead becomes important.

Instead of guessing, I tried some profiling to see the impact.
Unfortunately, the "sync" functions _do_ show up prominently at the top :/
What I'll do is attempting to make the sync logic smarter, eg most likely not all fields need to be copied, all the time. Hopefully this can reduce the sync overhead.


Independently of using the actual rerelease interface and all this...
Since you're working on extending protocol limits and have produced a "rereleasified" game library with the old interface, do you intend to merge these changes into the Q2PRO "main" at some point in the future?

**Comment by skullernet** [comment]
> But FWIW, overloading trace and triggering different behaviour by setting a specific bit in a pointer ... that's kind of hacky.

Well, it *is* a hack, as commit message says. Although using lower bits of a pointer to pass flags is nothing unusual, it is often used in e.g. Linux kernel. Maybe I will make `clip` a separate function exported through `GetExtendedGameAPI` someday.

> Happen, maybe, but there seems to be at least interest in such conversions

I see. Well it's those mod author's choice. Maybe they will continue to maintain two versions, one for old API, and one for new.

> Pmove is also entirely handled by the game (and cgame) module, so again in theory, it should be possible to retain any old behaviour here as well.

Yes, you are right. It might be possible to emulate old pmove behavior with new interface to some degree, didn't think of that.

> Unfortunately, the "sync" functions do show up prominently at the top

Honestly I can't think of a way to make this wrapper approach satisfactory. It will always be worse in performance due to the need to do data conversion. This is something I can't really accept in Q2PRO.

Realistically engine can support only one version of game interface. So for the time being, Q2PRO will stick to the old game API + protocol extensions to make re-release SP maps playable.

I think you can safely port Q2RTX to new game interface though. I don't think most of its users care about compatibility with older mods, they'll probably be happy with just re-release compatibility.

> Since you're working on extending protocol limits and have produced a "rereleasified" game library with the old interface, do you intend to merge these changes into the Q2PRO "main" at some point in the future?

Yes, it will be merged once I'm satisfied with it. I don't want to rush it, as I might still need to make changes to network protocol.

**Comment by Paril** [comment]
This isn't a huge deal but I did want to mention I have a plan to flesh out the cgame module much more than it currently is; Update 1 is released and none of that is in that update, but just to give a fair warning that if I get permission from id to do PC-only patches, the API will probably undergo one more major transformation before being finalized.

I basically wanted to "finish" the cgame implementation, because I didn't have the time to do so in the first iteration. I don't want to share the whole thing yet because it's a WIP, but just to give you a general idea of the scope, this is the current WIP game APIs - server game API 2024, client game API 2023:

https://gist.github.com/Paril/35e7ff2753efa6a96056216eacab6bf0

The goal is basically to move everything that I'm allowed to move into the cgame DLL that will implicitly become open source. It's essentially the bulk of the clients' handling of the view, the game and whatever - *similar* to Quake III's cgame, but with a tiny bit more control in some areas (like the cgame is now in charge of adding frame entities to the scene). The only thing that the cgame doesn't handle is raw input, frame decoding and menuing.

Hopefully this'll help other engines down the road to port our Kex-specific features as well since most of the source will be in the cgame now instead of hidden away in the client code.

The only bits I can't get open are the bots, which is the final missing "piece", but Mal is likely going to be OK with releasing the file format specs for the nav files. I will confer with him about that later.

**Comment by isadon** [comment]
> I'm not so sure... Although re-release changes nothing fundamentally in the engine, it touches enough important things that change game balance, specifically server tick rate and pmove precision. New players coming to Quake 2 may not care about it, but a lot of older players care. _Thus preserving original game interface and original gameplay should be an equally important goal._

Thank you. Prior to see this I had gone to Nightdive's Discord for the Quake 2 re-release and tried to make the case against their decision to not allow users to specify their player names in the UI (as Q2 has always allowed). Instead the player name is tied to what the user has specified in the platform in which they bought the game (steam, gog) and can only be changed through there or via running game with env variable USERNAME. After giving like 8 reasons why the old, simpler, original q2 method of just letting the player choose whatever name they want right from the game (not tied) to the platform, every single one was dismissed in favor of their "modern" UI. I say all this to say, no, the q2-re-release design choices don't have to be and most likely shouldn't be q2pro's.

The re-release sold me on various of the technical improvements but then left me dumbfounded with the change to not allow players to change names from the UI or providing a way to run in dedicated mode. If there is a way to run re-release in dedicated mode please let me know.

**Comment by skullernet** [comment]
Closing this. Supporting KEX game API in Q2PRO is not something that can realistically happen. Q2PRO supports its own game API extensions now that allow maps made for Quake 2 re-release to be playable with a [ported](https://github.com/skullernet/q2pro-rerelease-dll) game DLL.

**Pull request closed without merging**
