### PR TITLE
MD5 Support

### PR DESCRIPTION
**Pull request by Paril**
This is a PR for MD5 support; it's based on the work res2k and I are doing in the native re-release support fork.
The code is a bit of a mix of multiple sources, but they're all GPL-compatible - mainly http://tfc.duke.free.fr/coding/md5-specs-en.html and https://github.com/Novum/vkQuake
It's 100% functional and compatible with re-release models. Let me know if any changes need to be made for inclusion in q2pro.

The one thing I wanted to do was have a unified cvar for both models, but have it only be REFRESH latched if it was 0 without having initialized any models yet. I couldn't figure out a good approach for that so I just split it into two (one to allow loading the models, and one to "use" them, so you can flip back/forth between md5 and md2 versions like re-release). 

This also supports the required `md5scale` format extension, which is used for certain models (like the Enforcer) to allow bones to "pop" off or become hidden.

### CODE REVIEW

**Comment by skullernet** [comment]
Thanks! Seems to work well so far, and not as complex as I initially expected. Kinda sucks it needs a JSON parser, though. I'll play around with it to see if I find any issues and then I'll clean it up to match Q2PRO code style more and eventually merge it.

Having the ability to instantly switch between MD2/MD5 if useful for development, but eventually there should be only one cvar for enabling MD5. You can use CVAR_FILES for this purpose, changing it will flush registered media even if no models are loaded yet, but it's not as drastic as CVAR_REFRESH.

Some random comments regarding the code:
* Please use 4 spaces for indentation, your code seems to use a mix of tabs and spaces.
* You don't have to check return value of `Z_Malloc`, it's guaranteed to return non-NULL.
* New engine-specific math functions really belong to `common/math.c`, not `shared/shared.c`
* For loop variables it is preferable to use plain `int`, not fixed-width integer types.

**Comment by Paril** [comment]
In hindsight if I was designing `md5scale` again I wouldn't have used JSON - I basically only used it because we have jsoncpp readily available in Quake II Re-release and I didn't want to roll yet another parser.

The mixed tabs/spaces is probably because I have my IDE/git set up to ignore that and just treat everything as 4 space. I use tabs personally but have VS smoosh everything down to whatever it feels like. I think the initial copies of code laying around from the third party sources may have infected some of the files with tabs that confused VS or something.

Noted regarding math & loops.

It's a useful cvar for both development and just for the flip factor; the only thing is that the MD5 models take a lot longer to load, whereas the instantaneous flip was handy. I dunno what you'd prefer overall, though. If the MD5 is always going to be used without a restart, it'd be entirely possible to dump the MD2/MD3 models after they're loaded, but they'd still need to be loaded to get skins and bounds; alternatively the code could calculate skeletons to calculate bounds in the MD5 path so you'd only need to scan md2/md3 headers for skins but I don't know if it's worth the extra complexity.

**Comment by Paril** [comment]
Oh, I also haven't tested player models yet. You'll have to see if they still work.

**Comment by Paril** [comment]
There's a bug with normals that I still haven't been able to figure out; it seems to occur mostly when rotations are involved. You can see it easily with `spawn monster_guncmdr` and firing at him, his legs and gun have weird normals.

**Comment by skullernet** [comment]
I think normals issue has been fixed? Don't see anything wrong with `monster_guncmdr`.

I've kept both cvars by the way, since dumping MD2/MD3 models after loading is too annoying, so it works like you originally designed. Just shortened the cvar names.

Also replaced JSON parser with tiny custom parser that works for just `*.md5scale`.

Going to apply this. Thanks again!

**Comment by Paril** [comment]
Yeah @res2k found the issue with the normals and patched them.
Sounds good, thanks for the merge! Tiny custom parser is also a good enough compromise since the format is extremely static.

**Pull request closed without merging**
