### PR TITLE
remove calls to x86/fpu.c

### PR DESCRIPTION
**Pull request by sthalik**
#### Short description

The calls to `x86/fpu.c` break opentdm on i386 in a rather unusual fashion. See a [youtube video](https://www.youtube.com/watch?v=-P7B5ipNQ2s). In short, any movement causes the view to alternate between +45 and -45 roll or so. Strafe jump a few times then just walk around.

Thanks to @tojestzart for the video and the original report.

#### Operating system environment

- The host operating system is `FreeBSD 11.2-STABLE i386`. I've also observed the issue on other OS-en as long as it's a strictly 32-bit build.
- `CFLAGS` along with `CC` isn't anything special, i.e. `clang -O2 -march=geode -ggdb -fvisibility=hidden`.
- `SYS` is set to `Linux` since other code paths in `Makefile` depend on it.

The issue could only be observed when connecting to a dedicated server. Even if running on the same machine, even with a ping value of 1 ms.

#### Attempted explanation

It appears that without `#pragma FENV_ACCESS`, `<fenv.h>`, `fesetround(3)` and friends the compiler can confuse itself about the rounding modes. Furthermore, the removed code only deals with 387 math and never SSE2. One can imagine a scenario where `-mfpmath=sse` "fixes" the problem while `-mfpmath=both` makes it not deterministic...

Is there a particular *sensible* purpose for this code and pushing FP control word?

#### Guesswork

Perhaps the `.[ch]` files are a remnant of initial id code? I recommend removing all of inline assembly regardless, just as we did with "fast sqrt" (these days bound to introduce a pipeline stall).

I'm amused that opentdm's modify date is 2013-ish. Isn't there any bitrot?

### CODE REVIEW

**Comment by skullernet** [comment]
Can't reproduce on Debian testing. Tried building in `-m32` mode with these compilers:
* gcc version 8.2.0 (Debian 8.2.0-3)
* clang version 6.0.1-3 (tags/RELEASE_601/final)

However, I can reproduce similar effect if `bob_roll` variable is set to an oddly high value on the server. Can you confirm if `bob_*` variables are set to default values on the server?

As far as I remember, this x86/fpu.c stuff is needed to avoid prediction misses between client/server in player movement code due to excessive precision of x87 FPU operations, so it can't be simply removed.

**Comment by sthalik** [comment]
The `bob_*` values seem pretty same small fractions. Setting them all to zeroes works, but the gun remains invisible for movement's duration.

It didn't help was to compile with `gcc7 -O0 -fexcess-precision=standard -ffloat-store`.

Could it be related to the variable server FPS knob in either the server or the client?

In any case the original patch is bogus, hence closing.

**Comment by sthalik** [comment]
What helped was to run a Linux binary through an emulation layer on i386 FreeBSD. Unfortunately the issue is complex behavior so it's not something I could raise as a bug in the FreeBSD project itself. At least the workaround works.

**Comment by skullernet** [comment]
I was able to reproduce this bug in FreeBSD VM. Happens with default gamei386.so built from Q2PRO tree as well. Building with gcc7 installed from ports doesn't help either.

I'll look more into this. Good to know Linux emulation layer helps, but Q2PRO should be able to run on FreeBSD natively.

**Comment by skullernet** [comment]
Looks like math library functions break badly on FreeBSD if single precision mode is forced. Test case:

```
#include <stdio.h>
#include <math.h>
#include <ieeefp.h>

int main(void)
{
    fpsetprec(FP_PS);

    for (int i = 0; i < 40; i++)
        printf("%f\n", sin(i * M_PI / 4));

    return 0;
}
```

**Comment by sthalik** [comment]
Using openlibm (built with `-frounding-math`) for q2pro and opentdm (making sure `-lm` doesn't get pulled in) doesn't help either.

I'm going to try some more things. Note to self: build {q2pro,opentdm} with `-fno-builtin` when using openlibm. But compiler builtins should be the same across OS-en...

@skullernet I don't think this is worth the time for a practical purpose. amd64 and i686 will use SSE2 math exclusively, at least by default. `clang` shipped with newer FreeBSD versions doesn't support `-mfpmath=both`, only either-or. The only way a person could run into it is some other funky hardware like my network appliance box.

**Comment by skullernet** [comment]
> amd64 and i686 will use SSE2 math exclusively, at least by default

amd64 uses SSE2 math by default, but i686 target defaults to x87 FPU unless `-msse` (or `-msse2`) and `-mfpmath=sse` options are given. It makes this issue very real for all kind of i686 builds. I've tested Void linux with musl libc (i686-linux-musl) and this bug also happens there. The fact glibc sees no problem with reduced FPU precision seems to be more of exception rather than rule.

Thus I think the cleanest solution would be to accept this PR, removing FPU control word manipulation code like you originally suggested, and always build with `-msse -mfpmath=sse` for i686. (I've checked and enabling just SSE seems to be enough to avoid prediction misses). Resulting binaries won't run on anything before Pentium 3, but who cares.

**Comment by skullernet** [comment]
You can check this by building the amd64 client with CONFIG_DEBUG=y and enabling `cl_showmiss` cvar. Then connect to i686 dedicated server and try sliding along the non-axial walls, etc. If i686 server uses "broken" (extended precision) FPU math you'll see a bunch of messages like:

```
prediction miss on 323: 190 (-105 85 0)
prediction miss on 324: 366 (-119 119 128)
prediction miss on 325: 254 (-127 127 0)
prediction miss on 326: 416 (-144 144 128)
prediction miss on 327: 312 (-156 156 0)
prediction miss on 328: 510 (-191 191 128)
prediction miss on 329: 270 (-115 155 0)
```

(Note that respawning, or standing on moving objects such as plats will also produce these messages. This is by design though and not an error.)

You can also try connecting to original 3.20 quake2.exe dedicated server and observe no prediction errors, which means normal precision math model (achieved by building with SSE, or changing FPU control word) is the "correct" one.

**Comment by skullernet** [comment]
Merged your PR. Thanks for reporting this issue!

**Pull request closed without merging**
